apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . }}-volume
  labels:
    type: local
    app: {{ include "postgres.fullname" . }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ b64enc .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ b64enc .Values.postgres.password }}
  POSTGRES_DB: {{ b64enc .Values.postgres.db }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "postgres.fullname" . }}-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" . }}
    spec:
      containers:
        - name: {{ include "postgres.fullname" . }}
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "postgres.fullname" . }}-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: manual
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "postgres.fullname" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-public
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "postgres.fullname" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30032
