migration:
  image:
    repository: xxxxx
    tag: latest
    pullPolicy: IfNotPresent
  dir: xxxxx
  direction: up
  downTo: ""

database:
  host: xxxxx
  port: xxxxx
  user: xxxxx
  password: xxxxx
  name: xxxxx

  admin:
    user: xxxxx
    password: xxxxx
  url: xxxxx
